### ISSUE TITLE
Formatting nested translations

### ISSUE THREAD

**Issue by Czahoo** [i18next/i18next#1377]
Referring to [#977](https://github.com/i18next/i18next/issues/977#issuecomment-570253064) I am posting my case.

I have simple interpolation format config as follows:
```javascript
interpolation: {
            format: function(value, format) {
                if (format === 'uppercase' && typeof value === 'string') {
                    return value.toUpperCase();
                }
                if (format === 'lowercase' && typeof value === 'string') {
                    return value.toLowerCase();
                }
                return value;
            },
        },
```

When I'm trying to format nested string, only reference is getting formatted not actual text underneath it.

```yaml
# main.yml
example: "Black {{type, lowercase}} of {{attribute, lowercase}}"
```
```yaml
# other.yml
type:
  boots: Boots
attribute:
  str: Strength
```

Calling 
```javascript
i18n.t('main:example', {
  type: "$t('other:type.boots')",
  attribute: "$t('other:attribute.str')",
});
```
Results in `Black Boots of Strength` instead of `Black boots of strength` because `format` function receives `$t('other:type.boots')` and `$t('other:attribute.str')` as `value`, not `Boots` and `Strength` as intended.

In my case using
```javascript
i18n.t('main:example', {
  type: i18n.t('other:type.boots'),
  attribute: i18n.t('other:attribute.str'),
});
```
is out of the question unless I would manually parse every nested `$t(...)` because it is coming from backend.

The problem is that `format` function is called before parsing nested translations.

Thing get even more complicated when nested translation has more nested translations in it or further formatting. Imagine this:
```yaml
// another.yml
complex_case: "$t(main:example, { type: $t('another:big'), attribute: $t('other:attribute.str') })"
big: "Big $t('another:ugly', { param: '$t('other:type.boots')' })"
ugly: "Ugly {{param, uppercase}}"
```

Enough to say, that things get messy with any further level of nesting which makes it pointless to trying to "hack" current `format` behavior.
