### ISSUE TITLE
Change classes by a language.

### ISSUE THREAD

**Issue by dfdgsdfg** [i18next/i18next#412]
Hello. Is there any way change css classes by language? Or maybe the best practice?

I imagine like below. If we use a css selector of attribute, It's very useful.

```html
<span class="status" data-i18n="good"></span>
```
```json
{ 
  "en": {
    "good": "good"
  },
  "ko": {
    "good": "좋음"
  }
}
```
```css
.status[data-lang="en"] {
  color: red;
}

.status[data-lang="ko"] {
  color: blue;
}
```

- <https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors>
- <http://toddmotto.com/stop-toggling-classes-with-js-use-behaviour-driven-dom-manipulation-with-data-states/>

What about this? Or any other good option which I can use the right way?
